name: Docker Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development Docker image
        run: docker build -t classcorer-webapp:dev .

      - name: Build production Docker image
        run: docker build -t classcorer-webapp:prod -f Dockerfile.prod .

      - name: Test Docker Compose
        run: |
          cp .env.example .env
          docker-compose up -d
          sleep 10
          curl -f http://localhost:3000 || exit 1
          docker-compose down -v

      - name: Test Production Docker Compose (basic build only)
        run: |
          export NEXTAUTH_SECRET=testsecret
          export POSTGRES_PASSWORD=testpassword
          docker-compose -f docker-compose.prod.yml build 